### ISSUE TITLE
[FEATURE REQUEST] Recursive adding of files

### ISSUE THREAD

**Issue by schneidr** [limosoft-de/raffytimelapse#13]
Currently, when dropping a folder containing images on the application, the progressdialog only shows `0 from 0` and does nothing.

It should recursively enter the directory and subdirectories and add all found images.

**Comment by limosoft-de** [comment]
Thank you for this feature request. I agree, this is a desirable feature. I will keep this in mind for the next release

**Comment by limosoft-de** [comment]
Hi @schneidr 
the feature request was finally taken care of in https://github.com/limosoft-de/raffytimelapse/commit/7c25ea87592be2e683dfec9c4e94752254e68b5d. It will be rolled out in the next release 🎉 

Thank you again for the suggestion!

**Comment by limosoft-de** [comment]
Happy to announce that the feature is now released in [Version 2.3.0](https://github.com/limosoft-de/raffytimelapse/releases/tag/v2.3.0)! 🎉
