### ISSUE TITLE
[BUG] Installer choosing x86 directory on 64-bit machine

### ISSUE THREAD

**Issue by limosoft-de** [limosoft-de/raffytimelapse#18]
**Describe the bug**
While running installing procedure, the installer is writing into [windows path]/programs (x86) - as a 64-bit application.

**To Reproduce**
1. Use the Installer (e.g. Version 2.2.2) to Install Raffy Timelpase on a 64-bit machine

**Expected behavior**
The program will be installed in .../programs on a 64-bit machine.

**Symstem Information**
 - OS: Windows 10
 - Raffy Timelapse Version: 2.2.2

**Comment by limosoft-de** [comment]
This was first reported by @caissist in #14 

The issue seems to be, that Advanced Installer is faultly configuried to deploy as 32-bit package (see Package Definition ->Install Parameters). The AnyCPU copiled Raffy Timelapse binaries appear as 32-bit applications to Advanced Installer. The following options exist:

1. Deploy a mixed 32/64-bit Installer, using the AnyCPU compiled Raffy Timelapse binaries. (might not be possible, as Advanced Installer detects AnyCPU as 32-bit)
2. Deploy a mixed 32/64-bit Installer, using seperate 64 and 32-bit compiled Raffy Timelapse binaries.
3. Deploy seperate 32/64-bit Installers, using seperate 64 and 32-bit compiled Raffy Timelapse binaries.

**Comment by caissist** [comment]
> **Symstem Information**
> 
> * OS: Windows 10
> * Raffy Timelapse Version: 2.2.2

Correction: it was Windows 7 Prof. 64-bit, up-to-date

**Comment by limosoft-de** [comment]
Hi @caissist ,

I am happy to announce, that this will be fixed with the upcoming version of Raffy Timelapse. However, due to the functionality of the Windows Installer, if you choose to update Raffy Timelapse (rather than do a manual uninstall of the old version first), you will possibly still be offered to install Raffy Timelapse inside `C:\Program Files (x86)\...` by default.

This leaves you with two options:

1. Uninstall Raffy Timelapse manually and then install the new version once it's available and do not use the build in Update routine. The setup should now automatically suggest the 64-bit folder and not the x86.
~~2. Use the default update routine, but do change the path to `C:\Program Files\...` manually. From then on, each Update _should_ be installed in the 64-bit folder. If not, please try my first recommendation.~~

Thank you very much again for bringing this to my attention!

**Comment by limosoft-de** [comment]
Happy to announce that this is fixed in [Version 2.3.0](https://github.com/limosoft-de/raffytimelapse/releases/tag/v2.3.0)! 🎉

However, against my previous comment, please do follow suggestion 1 and perform a manual uninstall and then use the Installer .exe (**not** .msi!) to have a proper, clean 64-bit install of Raffy Timelapse. Thank you very much!
