### ISSUE TITLE
[QUESTION] Translating project

### ISSUE THREAD

**Issue by caissist** [limosoft-de/raffytimelapse#22]
I followed your link but found only an editor, no app's localizable resources?! 
Are you following Microsoft's Localization Rules? 
[(https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/guidelines-and-checklist-for-globalizing-your-app)] 

I have had some experience of localizing web projects and software - how can I do here?

**Comment by limosoft-de** [comment]
Hi @caissist ,

Yes, the link points to POEditor which is an online platform used for localizing resource files/strings in an online editor. That's absolutely wanted, as not every translator is an IT affine person who is willing to edit strings inside a .resx file for example. 

If you have some experience in localizing projects (like myself), you possibly know that many big open source software projects use a similar approach for translating their software, one of the many examples being WordPress. I am following this approach, as this allows more people to translate Raffy Timelapse in a simple way and it also enables me to keep a much better track of the progress of translations, as well as version control and moderation of individual translations.

Therefor, if you are interested in helping translate Raffy Timelapse, I would kindly ask you to use the POEditor project provided. While the raw translation files can be found in the source code [here](https://github.com/limosoft-de/raffytimelapse/tree/master/Raffy%20Timelapse) (see `strings_<countryCode>.resx`), this is currently not a valid way to contribute to the translations.

Also thank you for the link. However, it is part of the UWP Guidelines, while Raffy Timelapse is a Windows Forms Application where most of these Guidelines and API solutions are not available. As there are only very limited input options inside Raffy Timelapse, many of the recommendations are also simply not applicable to the software. Still thank you very much for your input on that matter.
