### ISSUE TITLE
[QUESTION] French isn't accessible in the application

### ISSUE THREAD

**Issue by clem-gb** [limosoft-de/raffytimelapse#26]
Hello,

i'm contacting you regarding the missing French translation, could you fix this please ?

Sincerely,

Nexinor

**Comment by limosoft-de** [comment]
Hi @Clgbt,
I assume you are the person, that very recently added the French translations to Poedior? In this case: Thank you very much for your contribution, I really appreciate it. :)

I will happily add the French translations with the next update. However, it might take a while until the next update is released, so please bear with me.

**Comment by limosoft-de** [comment]
Well, as an update was really overdue, I just released a new version.

As of 2.4.0 your new translations are included in Raffy Timelapse now @Clgbt 🥳

**Comment by clem-gb** [comment]
Thank you very much, I will probably fix some translations which doesn't fit the context
